spring.application.name=axion-academy
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5435/axion_academy
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true